src/controllers/teacher.ts, src/controllers/types/teacher.ts, src/models/migrations/1628083524817-test.ts, src/models/teacher.ts
=> Teacher API

src/middlewares/schema.ts
resolve GH-2
อันนี้ถ้าแก้เสร็จแล้ว API อันอื่นๆ น่าจะใช้ได้ด้วย เย้
เคสที่ส่ง column มั่วๆไป แล้วมันดันสำเร็จ ไม่ยอม error
=> [Fix] All API error not throw when unlisted property is sent

src/controllers/teacher.ts
resolve ceoss-kmitl/ceoss-frontend#12
=> [GH-12] Teacher CUD

src/controllers/room.ts, src/controllers/teacher.ts
resolve ceoss-kmitl/ceoss-frontend#15
=> [GH-15] Room API

src/libs/WebScrap.ts
=> [GH-20] Map teacher title from short to full

src/libs/WebScrap.ts, src/models/subject.ts
=> Fix web scrap teacher title mapper

src/controllers/subject.ts, src/controllers/webScrap.ts, src/models/migrations/1629350121291-UniqueSubjectCode.ts, src/models/subject.ts
close ceoss-kmitl/ceoss-frontend#13
=> [GH-13] Make subject code unique & edit web scrap loop

src/controllers/teacher.ts, src/controllers/types/teacher.ts, src/libs/WebScrap.ts, src/models/migrations/1629356782712-Add isActive column.ts, src/models/migrations/1629357315916-Remove CUD.ts, src/models/migrations/1629365851000-Unique.ts, src/models/teacher.ts
resolve  ceoss-kmitl/ceoss-frontend#37
=> [GH-37] Update Teacher model

src/controllers/room.ts, src/models/migrations/1629397388295-Update Room Table.ts, src/models/room.ts, src/models/teacher.ts
resolve ceoss-kmitl/ceoss-frontend#15
=> [GH-15] Remove CUD

src/controllers/subject.ts
close ceoss-kmitl/ceoss-frontend#13
=> [GH-13] Fix testcase edit same data

src/models/migrations/1629447980034-Unique.ts, src/models/room.ts
resolve ceoss-kmitl/ceoss-frontend#15
=> [GH-15] Unique

src/controllers/setting.ts, src/controllers/types/setting.ts, src/controllers/webScrap.ts, src/models/migrations/1629624887212-CreateSettingModel.ts, src/models/setting.ts
=> [GH-34] Setting API is OK

src/controllers/types/workload.ts, src/controllers/webScrap.ts, src/controllers/workload.ts, src/libs/mapper.ts, src/models/migrations/1629812038038-AddFieldOfStudyInWorkload.ts, src/models/workload.ts
=> [GH-40] Add fieldOfStudy & create workload endpoint

src/controllers/webScrap.ts, src/models/setting.ts
close ceoss-kmitl/ceoss-frontend#4
close GH-56
=> [GH-4]  Use url from setting to scrap data

src/controllers/setting.ts, src/controllers/types/setting.ts, src/models/migrations/1630157178329-Add vice-dean and SIIE director name.ts, src/models/migrations/1630161736970-Add vice dean and SIIE director name.ts, src/models/setting.ts
=> [GH-59] Add vice-dean  and SIIE director name

src/controllers/setting.ts, src/controllers/types/setting.ts, src/models/migrations/1630242155629-Add Inter cirriculum and external teacher pay rate.ts, src/models/setting.ts
=> [GH-62] Add Inter cirriculum and external teacher pay rate

src/controllers/webScrap.ts, src/libs/WebScrap.ts
=> [GH-57] Ignore subject of unknown teacher when scrap data

src/controllers/templates/workloadExcel1.ts, src/controllers/types/workload.ts, src/controllers/webScrap.ts, src/controllers/workload.ts, src/libs/Excel.ts, src/libs/WebScrap.ts, src/models/migrations/1630666460341-CreateTimeModel.ts, src/models/time.ts, src/models/workload.ts
=> [GH-52] Support break time now!

package.json, src/configs/ormconfig.ts, src/models/account.ts, src/models/migrations/1630820628336-SnakeCaseNaming.ts, src/models/subject.ts, src/models/teacher.ts, src/models/time.ts, src/models/workload.ts, yarn.lock
=> [GH-67] Config default naming strategies to snake_case

src/controllers/templates/workloadExcel2.ts, src/libs/Excel.ts
=> [GH-41] Workload Excel file 2

src/models/migrations/1630841915076-CascadeTimeWorkload.ts, src/models/time.ts
close ceoss-kmitl/ceoss-frontend#49
=> [GH-49] Make TimeModel cascade when delete

src/controllers/types/workload.ts, src/controllers/webScrap.ts, src/controllers/workload.ts, src/models/migrations/1631011286420-AddDegreeInWorkload.ts, src/models/workload.ts
=> [GH-75] Add degree in workload model

src/controllers/teacher.ts, src/controllers/types/teacher.ts, src/controllers/webScrap.ts, src/models/migrations/1631105169035-EditIsExecutiveToString.ts, src/models/teacher.ts
=> [GH-78] Edit isExecutive to executiveRole

src/controllers/templates/workloadExcel2.ts
=> [GH-41] Update file 2

src/controllers/subject.ts, src/controllers/webScrap.ts, src/models/migrations/1631262739927-OnDeleteSubjectCascade.ts, src/models/workload.ts
=> Fix cant remove subject

src/libs/Excel.ts
=> [GH-77] Add number format to ExcelJS

src/controllers/account.ts, src/controllers/room.ts, src/controllers/subject.ts, src/controllers/teacher.ts, src/controllers/templates/workloadExcel1.ts, src/controllers/templates/workloadExcel2.ts, src/controllers/webScrap.ts, src/controllers/workload.ts, src/errors/badRequestError.ts, src/errors/baseError.ts, src/errors/internalServerError.ts, src/errors/notFoundError.ts, src/errors/schemaError.ts, src/middlewares/errorHandler.ts, src/middlewares/schema.ts
=> [GH-83] Update err msg

src/configs/database.ts, src/controllers/templates/workloadExcel1.ts, src/controllers/templates/workloadExcel2.ts, src/controllers/types/workload.ts, src/controllers/webScrap.ts, src/controllers/workload.ts, src/libs/mapper.ts, src/models/migrations/1632229044686-AddTeacherWorkload.ts, src/models/migrations/1632901897137-AddExplicitTeacherWorkload.ts, src/models/teacher.ts, src/models/teacherWorkload.ts, src/models/time.ts, src/models/workload.ts
close ceoss-kmitl/ceoss-frontend#74
=> [GH-74] Refactor TeacherWorkload

src/controllers/templates/workloadExcel3.ts, src/controllers/types/workload.ts, src/controllers/webScrap.ts, src/controllers/workload.ts, src/libs/Excel.ts, src/libs/mapper.ts
=> [GH-24] Excel file 3

src/controllers/templates/workloadExcel3Out.ts, src/controllers/types/workload.ts, src/controllers/workload.ts, src/models/subject.ts
=> [GH-43] excel3 outsider

src/controllers/templates/workloadExcel1.ts, src/controllers/templates/workloadExcel2.ts, src/controllers/templates/workloadExcel3.ts, src/libs/Excel.ts, src/models/teacher.ts
=> [GH-91] Recheck excel1, 2 after change TeacherWorkload

src/controllers/templates/workloadExcel3.ts
=> [GH-24] Fix endTime & workload hrs at top right

src/models/migrations/1635603651651-ChangeWeekCountToFloat.ts, src/models/teacherWorkload.ts
=> [GH-96] Change weekCount to float

src/constants/room.ts, src/controllers/room.ts, src/controllers/templates/roomExcel.ts, src/controllers/types/room.ts
=> [GH-105] Add room excel endpoint

src/controllers/subject.ts
close ceoss-kmitl/ceoss-frontend#9
=> [GH-9] Add delete compensated endpoint

src/controllers/subject.ts, src/controllers/types/workload.ts, src/controllers/workload.ts
close ceoss-kmitl/ceoss-frontend#10
=> [GH-10] Update API TA system, support multiple dayList as one

src/controllers/templates/assistantExcel1.ts, src/models/migrations/1643378609825-AddTApayRateInterAndAddSettingDefaultValue.ts, src/models/setting.ts
=> [GH-25] Add pay rate inter for TA

package.json, src/configs/server.ts, src/controllers/account.ts, src/controllers/room.ts, src/controllers/setting.ts, src/controllers/subject.ts, src/controllers/teacher.ts, src/controllers/webScrap.ts, src/controllers/workload.ts, src/middlewares/errorHandler.ts, src/models/account.ts, src/models/migrations/1643447734975-UpdateAccountModel.ts, yarn.lock
close ceoss-kmitl/ceoss-frontend#16
=> [GH-16] Apply auth to server

src/constants/room.ts, src/controllers/room.ts, src/controllers/types/subject.ts, src/controllers/types/workload.ts, src/controllers/workload.ts, src/models/migrations/1643610203585-AddRequiredRoomIntoSubject.ts, src/models/subject.ts
=> [GH-121] Support requiredRoom option in Subject

src/controllers/subject.ts, src/controllers/templates/assistantExcel2.ts
=> TA Excel file 2

src/controllers/sync.ts, src/controllers/types/sync.ts
close ceoss-kmitl/ceoss-frontend#97
=> [GH-97] Add new SyncController

src/controllers/sync.ts, src/controllers/types/sync.ts
close ceoss-kmitl/ceoss-frontend#96
=> [GH-96] Able to sync subject

src/controllers/templates/assistantExcel1.ts
close ceoss-kmitl/ceoss-frontend#106
=> [GH-106] Fix TA excel1 - filter by sent month

src/controllers/templates/assistantExcel2.ts
=> support 5 days / month

src/controllers/types/setting.ts
close ceoss-kmitl/ceoss-frontend#129
=> [GH-129] fix type
